module.exports = {
  env: {
    node: true,
    jest: true,
  },
  parserOptions: {
    ecmaVersion: "latest",
    sourceType: "module",
  },
  plugins: ["jest"],
  rules: {
    "jest/consistent-test-it": "error",
    "jest/expect-expect": "warn",
    "jest/max-nested-describe": [
      "warn",
      {
        max: 5,
      },
    ],
    "jest/no-alias-methods": "error",
    "jest/no-commented-out-tests": "off",
    "jest/no-conditional-expect": "warn",
    "jest/no-conditional-in-test": "off",
    "jest/no-deprecated-functions": "error",
    "jest/no-disabled-tests": "off",
    "jest/no-done-callback": "off",
    "jest/no-duplicate-hooks": "error",
    "jest/no-exports": "error",
    "jest/no-focused-tests": "warn",
    "jest/no-hooks": "off",
    "jest/no-identical-title": "warn",
    "jest/no-interpolation-in-snapshots": "off",
    "jest/no-jasmine-globals": "off",
    "jest/no-jest-import": "error",
    "jest/no-large-snapshots": "off",
    "jest/no-mocks-import": "off",
    "jest/jest/no-restricted-matchers": "off",
    "jest/no-standalone-expect": "warn",
    "jest/no-test-prefixes": "error",
    "jest/no-test-return-statement": "error",
    "jest/prefer-called-with": "off",
    "jest/prefer-comparison-matcher": "error",
    "jest/prefer-equality-matcher": "error",
    "jest/prefer-expect-assertions": "off",
    "jest/prefer-expect-resolves": "off",
    "jest/prefer-hooks-on-top": "warn",
    "jest/prefer-lowercase-title": "warn",
    "jest/prefer-snapshot-hint": "off",
    "jest/prefer-spy-on": "warn",
    "jest/prefer-strict-equal": "off",
    "jest/prefer-to-be": "off",
    "jest/prefer-to-contain": "warn",
    "jest/prefer-to-have-length": "warn",
    "jest/prefer-todo": "warn",
    "jest/require-hook": "off",
    "jest/require-to-throw-message": "off",
    "jest/require-top-level-describe": "error",
    "jest/valid-describe-callback": "warn",
    "jest/valid-expect": "warn",
    "jest/valid-expect-in-promise": "warn",
    "jest/valid-title": "warn",
  },
};
